### ISSUE TITLE
Build initial skeleton

### ISSUE THREAD

**Issue by nicholaswmin** [TheProfs/media-parser#1]
## Todos

Following [TDD practices][1]

### Tests

- [x] Add unit tests for following modules
 - `pdf-parser`  (parse PDF to images)
 - `s3-mapper`(saves local images to S3 and returns file paths)`
- [x] Add API tests
 - `/upload`

### Actual code

- [x] Build modules
- [x] Build a POST `/upload` API endpoint

[1]: https://en.wikipedia.org/wiki/Test-driven_development

**Comment by nicholaswmin** [comment]
Closed in #2
